// const generateMockSkillTree = useCallback((prompt: string): SkillTree => {
//     const templates: { [key: string]: Omit<SkillNode, 'iconName'>[] } = {
//         frontend: [
//             {
//                 id: 'html5',
//                 name: 'HTML5',
//                 description: 'Master semantic HTML5 structure',
//                 gridPosition: { x: 2, y: 0 },
//                 dependencies: [],
//                 questId: 'html-quest',
//                 isUnlocked: true,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'css3',
//                 name: 'CSS3',
//                 description: 'Style with modern CSS3',
//                 gridPosition: { x: 1, y: 1 },
//                 dependencies: ['html5'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'javascript',
//                 name: 'JavaScript',
//                 description: 'Interactive web programming',
//                 gridPosition: { x: 3, y: 1 },
//                 dependencies: ['html5'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'responsive',
//                 name: 'Responsive Design',
//                 description: 'Mobile-first and adaptive layouts',
//                 gridPosition: { x: 0, y: 2 },
//                 dependencies: ['css3'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 80,
//                 currentPoints: 0
//             },
//             {
//                 id: 'css-frameworks',
//                 name: 'CSS Frameworks',
//                 description: 'Bootstrap, Tailwind, etc.',
//                 gridPosition: { x: 1, y: 2 },
//                 dependencies: ['css3'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 70,
//                 currentPoints: 0
//             },
//             {
//                 id: 'dom',
//                 name: 'DOM Manipulation',
//                 description: 'Dynamic interface manipulation',
//                 gridPosition: { x: 3, y: 2 },
//                 dependencies: ['javascript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'es6-plus',
//                 name: 'ES6+',
//                 description: 'Modern JavaScript features',
//                 gridPosition: { x: 4, y: 2 },
//                 dependencies: ['javascript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'typescript',
//                 name: 'TypeScript',
//                 description: 'Typed JavaScript development',
//                 gridPosition: { x: 5, y: 3 },
//                 dependencies: ['es6-plus'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'sass',
//                 name: 'Sass/SCSS',
//                 description: 'CSS preprocessors',
//                 gridPosition: { x: 1, y: 3 },
//                 dependencies: ['css-frameworks'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 80,
//                 currentPoints: 0
//             },
//             {
//                 id: 'react',
//                 name: 'React',
//                 description: 'Component-based UI library',
//                 gridPosition: { x: 3, y: 3 },
//                 dependencies: ['dom', 'es6-plus'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             },
//             {
//                 id: 'state-management',
//                 name: 'State Management',
//                 description: 'Redux, Context API, etc.',
//                 gridPosition: { x: 2, y: 4 },
//                 dependencies: ['react'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 130,
//                 currentPoints: 0
//             },
//             {
//                 id: 'react-hooks',
//                 name: 'React Hooks',
//                 description: 'Functional component patterns',
//                 gridPosition: { x: 3, y: 4 },
//                 dependencies: ['react'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'nextjs',
//                 name: 'Next.js',
//                 description: 'React framework for production',
//                 gridPosition: { x: 4, y: 4 },
//                 dependencies: ['react', 'typescript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'testing',
//                 name: 'Testing',
//                 description: 'Unit and integration testing',
//                 gridPosition: { x: 1, y: 5 },
//                 dependencies: ['state-management'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'performance',
//                 name: 'Performance',
//                 description: 'Web performance optimization',
//                 gridPosition: { x: 3, y: 5 },
//                 dependencies: ['react-hooks'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'advanced-patterns',
//                 name: 'Advanced Patterns',
//                 description: 'Advanced React patterns',
//                 gridPosition: { x: 4, y: 5 },
//                 dependencies: ['nextjs'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             }
//         ],
//         backend: [
//             {
//                 id: 'programming-fundamentals',
//                 name: 'Programming Fundamentals',
//                 description: 'Core programming concepts',
//                 gridPosition: { x: 2, y: 0 },
//                 dependencies: [],
//                 questId: 'html-quest',
//                 isUnlocked: true,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'version-control',
//                 name: 'Version Control',
//                 description: 'Git and collaboration',
//                 gridPosition: { x: 0, y: 1 },
//                 dependencies: ['programming-fundamentals'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 80,
//                 currentPoints: 0
//             },
//             {
//                 id: 'nodejs',
//                 name: 'Node.js',
//                 description: 'Server-side JavaScript runtime',
//                 gridPosition: { x: 2, y: 1 },
//                 dependencies: ['programming-fundamentals'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'python',
//                 name: 'Python',
//                 description: 'Versatile backend language',
//                 gridPosition: { x: 4, y: 1 },
//                 dependencies: ['programming-fundamentals'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'express',
//                 name: 'Express.js',
//                 description: 'Web framework for Node.js',
//                 gridPosition: { x: 1, y: 2 },
//                 dependencies: ['nodejs'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'api-design',
//                 name: 'API Design',
//                 description: 'RESTful API development',
//                 gridPosition: { x: 2, y: 2 },
//                 dependencies: ['nodejs'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 130,
//                 currentPoints: 0
//             },
//             {
//                 id: 'django',
//                 name: 'Django',
//                 description: 'Python web framework',
//                 gridPosition: { x: 4, y: 2 },
//                 dependencies: ['python'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'sql',
//                 name: 'SQL',
//                 description: 'Relational database querying',
//                 gridPosition: { x: 0, y: 3 },
//                 dependencies: ['express'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'mongodb',
//                 name: 'MongoDB',
//                 description: 'NoSQL document database',
//                 gridPosition: { x: 1, y: 3 },
//                 dependencies: ['express'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 130,
//                 currentPoints: 0
//             },
//             {
//                 id: 'graphql',
//                 name: 'GraphQL',
//                 description: 'Query language for APIs',
//                 gridPosition: { x: 3, y: 3 },
//                 dependencies: ['api-design'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'authentication',
//                 name: 'Authentication',
//                 description: 'Security and user management',
//                 gridPosition: { x: 2, y: 4 },
//                 dependencies: ['api-design', 'mongodb'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 160,
//                 currentPoints: 0
//             },
//             {
//                 id: 'testing-backend',
//                 name: 'Backend Testing',
//                 description: 'Unit, integration, and e2e tests',
//                 gridPosition: { x: 1, y: 5 },
//                 dependencies: ['authentication'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'containerization',
//                 name: 'Containerization',
//                 description: 'Docker and container tech',
//                 gridPosition: { x: 3, y: 5 },
//                 dependencies: ['authentication'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'cloud-deployment',
//                 name: 'Cloud Deployment',
//                 description: 'AWS, Azure, GCP',
//                 gridPosition: { x: 2, y: 6 },
//                 dependencies: ['testing-backend', 'containerization'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'microservices',
//                 name: 'Microservices',
//                 description: 'Distributed architecture',
//                 gridPosition: { x: 3, y: 6 },
//                 dependencies: ['containerization'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             }
//         ],
//         ai: [
//             {
//                 id: 'python',
//                 name: 'Python',
//                 description: 'Programming language for AI/ML',
//                 gridPosition: { x: 2, y: 0 },
//                 dependencies: [],
//                 questId: 'html-quest',
//                 isUnlocked: true,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'math-foundations',
//                 name: 'Math Foundations',
//                 description: 'Linear algebra, calculus, statistics',
//                 gridPosition: { x: 1, y: 1 },
//                 dependencies: ['python'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'data-manipulation',
//                 name: 'Data Manipulation',
//                 description: 'NumPy and Pandas',
//                 gridPosition: { x: 3, y: 1 },
//                 dependencies: ['python'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'data-visualization',
//                 name: 'Data Visualization',
//                 description: 'Matplotlib, Seaborn, Plotly',
//                 gridPosition: { x: 3, y: 2 },
//                 dependencies: ['data-manipulation'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'statistical-analysis',
//                 name: 'Statistical Analysis',
//                 description: 'Hypothesis testing, inference',
//                 gridPosition: { x: 0, y: 2 },
//                 dependencies: ['math-foundations'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 130,
//                 currentPoints: 0
//             },
//             {
//                 id: 'ml-fundamentals',
//                 name: 'ML Fundamentals',
//                 description: 'Core ML concepts',
//                 gridPosition: { x: 1, y: 2 },
//                 dependencies: ['math-foundations'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'supervised-learning',
//                 name: 'Supervised Learning',
//                 description: 'Regression and classification',
//                 gridPosition: { x: 1, y: 3 },
//                 dependencies: ['ml-fundamentals', 'data-manipulation'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'unsupervised-learning',
//                 name: 'Unsupervised Learning',
//                 description: 'Clustering and dimensionality reduction',
//                 gridPosition: { x: 2, y: 3 },
//                 dependencies: ['ml-fundamentals', 'data-visualization'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 160,
//                 currentPoints: 0
//             },
//             {
//                 id: 'scikit-learn',
//                 name: 'Scikit-learn',
//                 description: 'ML library implementation',
//                 gridPosition: { x: 0, y: 4 },
//                 dependencies: ['supervised-learning'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'deep-learning',
//                 name: 'Deep Learning',
//                 description: 'Neural networks fundamentals',
//                 gridPosition: { x: 3, y: 4 },
//                 dependencies: ['supervised-learning', 'unsupervised-learning'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             },
//             {
//                 id: 'tensorflow',
//                 name: 'TensorFlow',
//                 description: 'Deep learning framework',
//                 gridPosition: { x: 2, y: 5 },
//                 dependencies: ['deep-learning'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'pytorch',
//                 name: 'PyTorch',
//                 description: 'Dynamic neural network library',
//                 gridPosition: { x: 4, y: 5 },
//                 dependencies: ['deep-learning'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'nlp',
//                 name: 'Natural Language Processing',
//                 description: 'Text processing and understanding',
//                 gridPosition: { x: 1, y: 6 },
//                 dependencies: ['tensorflow'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 190,
//                 currentPoints: 0
//             },
//             {
//                 id: 'computer-vision',
//                 name: 'Computer Vision',
//                 description: 'Image and video analysis',
//                 gridPosition: { x: 3, y: 6 },
//                 dependencies: ['pytorch'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 190,
//                 currentPoints: 0
//             },
//             {
//                 id: 'generative-ai',
//                 name: 'Generative AI',
//                 description: 'GANs, diffusion models, LLMs',
//                 gridPosition: { x: 2, y: 7 },
//                 dependencies: ['nlp', 'computer-vision'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 250,
//                 currentPoints: 0
//             },
//             {
//                 id: 'ai-ethics',
//                 name: 'AI Ethics & Responsibility',
//                 description: 'Ethical AI development',
//                 gridPosition: { x: 4, y: 7 },
//                 dependencies: ['generative-ai'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             }
//         ],
//         mobile: [
//             {
//                 id: 'mobile-fundamentals',
//                 name: 'Mobile Fundamentals',
//                 description: 'Mobile development basics',
//                 gridPosition: { x: 2, y: 0 },
//                 dependencies: [],
//                 questId: 'html-quest',
//                 isUnlocked: true,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'javascript',
//                 name: 'JavaScript',
//                 description: 'Programming language basics',
//                 gridPosition: { x: 1, y: 1 },
//                 dependencies: ['mobile-fundamentals'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'mobile-ui-design',
//                 name: 'Mobile UI Design',
//                 description: 'Design principles for mobile',
//                 gridPosition: { x: 3, y: 1 },
//                 dependencies: ['mobile-fundamentals'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 110,
//                 currentPoints: 0
//             },
//             {
//                 id: 'react-native',
//                 name: 'React Native',
//                 description: 'Cross-platform mobile development',
//                 gridPosition: { x: 1, y: 2 },
//                 dependencies: ['javascript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'flutter',
//                 name: 'Flutter',
//                 description: 'Google\'s UI toolkit for mobile',
//                 gridPosition: { x: 3, y: 2 },
//                 dependencies: ['mobile-ui-design'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'ios-swift',
//                 name: 'iOS & Swift',
//                 description: 'Native iOS development',
//                 gridPosition: { x: 5, y: 2 },
//                 dependencies: ['mobile-ui-design'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             },
//             {
//                 id: 'android-kotlin',
//                 name: 'Android & Kotlin',
//                 description: 'Native Android development',
//                 gridPosition: { x: 0, y: 2 },
//                 dependencies: ['javascript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             },
//             {
//                 id: 'mobile-navigation',
//                 name: 'Mobile Navigation',
//                 description: 'Screen flows and navigation',
//                 gridPosition: { x: 2, y: 3 },
//                 dependencies: ['react-native', 'flutter'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'state-management',
//                 name: 'State Management',
//                 description: 'Redux, MobX, Provider',
//                 gridPosition: { x: 1, y: 4 },
//                 dependencies: ['mobile-navigation'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'device-apis',
//                 name: 'Device APIs',
//                 description: 'Camera, sensors, location',
//                 gridPosition: { x: 3, y: 4 },
//                 dependencies: ['mobile-navigation'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'data-persistence',
//                 name: 'Data Persistence',
//                 description: 'Local storage and databases',
//                 gridPosition: { x: 2, y: 5 },
//                 dependencies: ['state-management', 'device-apis'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 130,
//                 currentPoints: 0
//             },
//             {
//                 id: 'app-testing',
//                 name: 'Mobile App Testing',
//                 description: 'Unit, UI, and integration tests',
//                 gridPosition: { x: 1, y: 6 },
//                 dependencies: ['data-persistence'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'app-publishing',
//                 name: 'App Store Publishing',
//                 description: 'App store submission process',
//                 gridPosition: { x: 3, y: 6 },
//                 dependencies: ['data-persistence'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 110,
//                 currentPoints: 0
//             },
//             {
//                 id: 'performance-optimization',
//                 name: 'Performance Optimization',
//                 description: 'Speed and efficiency tuning',
//                 gridPosition: { x: 2, y: 7 },
//                 dependencies: ['app-testing', 'app-publishing'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 170,
//                 currentPoints: 0
//             }
//         ],
//         fullstack: [
//             {
//                 id: 'programming-basics',
//                 name: 'Programming Basics',
//                 description: 'Core programming concepts',
//                 gridPosition: { x: 3, y: 0 },
//                 dependencies: [],
//                 questId: 'html-quest',
//                 isUnlocked: true,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'html-css',
//                 name: 'HTML & CSS',
//                 description: 'Web structure and styling',
//                 gridPosition: { x: 1, y: 1 },
//                 dependencies: ['programming-basics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'javascript',
//                 name: 'JavaScript',
//                 description: 'Web programming language',
//                 gridPosition: { x: 3, y: 1 },
//                 dependencies: ['programming-basics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'git',
//                 name: 'Git & GitHub',
//                 description: 'Version control systems',
//                 gridPosition: { x: 5, y: 1 },
//                 dependencies: ['programming-basics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 90,
//                 currentPoints: 0
//             },
//             {
//                 id: 'web-design',
//                 name: 'Web Design',
//                 description: 'UI/UX principles for web',
//                 gridPosition: { x: 0, y: 2 },
//                 dependencies: ['html-css'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'css-frameworks',
//                 name: 'CSS Frameworks',
//                 description: 'Bootstrap, Tailwind, etc.',
//                 gridPosition: { x: 1, y: 2 },
//                 dependencies: ['html-css'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 80,
//                 currentPoints: 0
//             },
//             {
//                 id: 'es6-modern-js',
//                 name: 'ES6+ JavaScript',
//                 description: 'Modern JavaScript features',
//                 gridPosition: { x: 3, y: 2 },
//                 dependencies: ['javascript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'typescript',
//                 name: 'TypeScript',
//                 description: 'Typed JavaScript superset',
//                 gridPosition: { x: 4, y: 2 },
//                 dependencies: ['javascript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'frontend-framework',
//                 name: 'Frontend Framework',
//                 description: 'React, Vue, or Angular',
//                 gridPosition: { x: 2, y: 3 },
//                 dependencies: ['css-frameworks', 'es6-modern-js'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             },
//             {
//                 id: 'nodejs',
//                 name: 'Node.js',
//                 description: 'JavaScript runtime',
//                 gridPosition: { x: 4, y: 3 },
//                 dependencies: ['es6-modern-js', 'typescript'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'frontend-state',
//                 name: 'State Management',
//                 description: 'Redux, Vuex, Context, etc.',
//                 gridPosition: { x: 1, y: 4 },
//                 dependencies: ['frontend-framework'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 130,
//                 currentPoints: 0
//             },
//             {
//                 id: 'api-consumption',
//                 name: 'API Consumption',
//                 description: 'HTTP clients and data fetching',
//                 gridPosition: { x: 2, y: 4 },
//                 dependencies: ['frontend-framework'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 110,
//                 currentPoints: 0
//             },
//             {
//                 id: 'backend-framework',
//                 name: 'Backend Framework',
//                 description: 'Express, Nest.js, etc.',
//                 gridPosition: { x: 4, y: 4 },
//                 dependencies: ['nodejs'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 160,
//                 currentPoints: 0
//             },
//             {
//                 id: 'databases',
//                 name: 'Databases',
//                 description: 'SQL and NoSQL databases',
//                 gridPosition: { x: 5, y: 4 },
//                 dependencies: ['nodejs'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 170,
//                 currentPoints: 0
//             },
//             {
//                 id: 'authentication',
//                 name: 'Authentication',
//                 description: 'User auth and security',
//                 gridPosition: { x: 3, y: 5 },
//                 dependencies: ['api-consumption', 'backend-framework'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'testing',
//                 name: 'Testing',
//                 description: 'Frontend and backend testing',
//                 gridPosition: { x: 2, y: 6 },
//                 dependencies: ['authentication'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'deployment',
//                 name: 'Deployment',
//                 description: 'CI/CD and cloud hosting',
//                 gridPosition: { x: 4, y: 6 },
//                 dependencies: ['authentication'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'advanced-fullstack',
//                 name: 'Advanced Full-Stack',
//                 description: 'Specialized integrations',
//                 gridPosition: { x: 3, y: 7 },
//                 dependencies: ['testing', 'deployment'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             }
//         ],
//         gamedev: [
//             {
//                 id: 'programming-basics',
//                 name: 'Programming Basics',
//                 description: 'Core programming concepts',
//                 gridPosition: { x: 2, y: 0 },
//                 dependencies: [],
//                 questId: 'html-quest',
//                 isUnlocked: true,
//                 isCompleted: false,
//                 maxPoints: 100,
//                 currentPoints: 0
//             },
//             {
//                 id: 'game-design',
//                 name: 'Game Design',
//                 description: 'Principles of game design',
//                 gridPosition: { x: 0, y: 1 },
//                 dependencies: ['programming-basics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'c-sharp',
//                 name: 'C#',
//                 description: 'Game programming language',
//                 gridPosition: { x: 2, y: 1 },
//                 dependencies: ['programming-basics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: 'digital-art',
//                 name: 'Digital Art',
//                 description: 'Game art creation',
//                 gridPosition: { x: 4, y: 1 },
//                 dependencies: ['programming-basics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             },
//             {
//                 id: 'unity-basics',
//                 name: 'Unity Basics',
//                 description: 'Unity engine fundamentals',
//                 gridPosition: { x: 1, y: 2 },
//                 dependencies: ['c-sharp'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'unreal-basics',
//                 name: 'Unreal Basics',
//                 description: 'Unreal engine fundamentals',
//                 gridPosition: { x: 3, y: 2 },
//                 dependencies: ['c-sharp'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: '2d-game-dev',
//                 name: '2D Game Development',
//                 description: 'Creating 2D games',
//                 gridPosition: { x: 0, y: 3 },
//                 dependencies: ['unity-basics', 'game-design'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 160,
//                 currentPoints: 0
//             },
//             {
//                 id: 'game-physics',
//                 name: 'Game Physics',
//                 description: 'Physics systems in games',
//                 gridPosition: { x: 2, y: 3 },
//                 dependencies: ['unity-basics', 'unreal-basics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 140,
//                 currentPoints: 0
//             },
//             {
//                 id: '3d-modeling',
//                 name: '3D Modeling',
//                 description: 'Creating 3D game assets',
//                 gridPosition: { x: 4, y: 3 },
//                 dependencies: ['unreal-basics', 'digital-art'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 170,
//                 currentPoints: 0
//             },
//             {
//                 id: '3d-game-dev',
//                 name: '3D Game Development',
//                 description: 'Creating 3D games',
//                 gridPosition: { x: 3, y: 4 },
//                 dependencies: ['game-physics', '3d-modeling'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 190,
//                 currentPoints: 0
//             },
//             {
//                 id: 'game-ai',
//                 name: 'Game AI',
//                 description: 'Artificial intelligence in games',
//                 gridPosition: { x: 1, y: 4 },
//                 dependencies: ['game-physics'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 160,
//                 currentPoints: 0
//             },
//             {
//                 id: 'multiplayer',
//                 name: 'Multiplayer',
//                 description: 'Networking for games',
//                 gridPosition: { x: 2, y: 5 },
//                 dependencies: ['game-ai', '3d-game-dev'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 180,
//                 currentPoints: 0
//             },
//             {
//                 id: 'game-optimization',
//                 name: 'Game Optimization',
//                 description: 'Performance tuning',
//                 gridPosition: { x: 4, y: 5 },
//                 dependencies: ['3d-game-dev'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 150,
//                 currentPoints: 0
//             },
//             {
//                 id: 'advanced-gamedev',
//                 name: 'Advanced Game Development',
//                 description: 'Complex game systems',
//                 gridPosition: { x: 3, y: 6 },
//                 dependencies: ['multiplayer', 'game-optimization'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 200,
//                 currentPoints: 0
//             },
//             {
//                 id: 'game-publishing',
//                 name: 'Game Publishing',
//                 description: 'Releasing and marketing games',
//                 gridPosition: { x: 3, y: 7 },
//                 dependencies: ['advanced-gamedev'],
//                 questId: 'html-quest',
//                 isUnlocked: false,
//                 isCompleted: false,
//                 maxPoints: 120,
//                 currentPoints: 0
//             }
//         ]
//     };